/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_christianaberger_cpptest_Mushroom */

#ifndef _Included_com_example_christianaberger_cpptest_Mushroom
#define _Included_com_example_christianaberger_cpptest_Mushroom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_christianaberger_cpptest_Mushroom
 * Method:    computeSchwammerlType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_christianaberger_cpptest_Mushroom_computeSchwammerlType
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
